language: generic
sudo: required
services:
  - docker
before-install:
  - docker build -t mkoujalgi96/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true mkoujalgi96/docker-react npm run test
