language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t build -f Dockerfile.dev .
script:
  - docker run -e CI=true build npm run test
deploy:
  provider: elasticbeanstalk
  region: 
  app: "docker-react"
  env: "Docker-env"
  bucket_name:
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
